module.exports = {
  ".checkbox-": {
    "$on": {
      "paddingY": "0px",
      "paddingX": "0px",
      "paddingTop": "0px",
      "paddingRight": "0px",
      "paddingBottom": "0px",
      "paddingLeft": "0px",
      "paddingStart": "0px",
      "paddingEnd": "0px",
      "spacing": "12px",
      "opacity": "1",
      "color": "#ffffff",
      "borderWidth": "1px",
      "borderRadius": "3px",
      "borderColor": "rgba(0, 0, 0, 0)",
      "width": "12.599609375px",
      "widthRaw": "12.599609375",
      "height": "12.5999755859375px",
      "heightRaw": "12.5999755859375",
      "fontFamily": "'Inter'",
      "fontSize": "14px",
      "fontWeight": "400",
      "lineHeight": "1.4285714721679688",
      "letterSpacing": "-0.28px",
      "textAlign": "left",
      "textDecoration": "none",
      "textTransform": "none",
      "boxShadow": "none"
    },
    "$off": {
      "paddingY": "0px",
      "paddingX": "0px",
      "paddingTop": "0px",
      "paddingRight": "0px",
      "paddingBottom": "0px",
      "paddingLeft": "0px",
      "paddingStart": "0px",
      "paddingEnd": "0px",
      "spacing": "12px",
      "opacity": "1",
      "color": "#ffffff",
      "borderWidth": "1px",
      "borderRadius": "3px",
      "borderColor": "#b3b3b3",
      "width": "18px",
      "widthRaw": "18",
      "height": "18px",
      "heightRaw": "18",
      "fontFamily": "'Inter'",
      "fontSize": "14px",
      "fontWeight": "400",
      "lineHeight": "1.4285714721679688",
      "letterSpacing": "-0.28px",
      "textAlign": "left",
      "textDecoration": "none",
      "textTransform": "none",
      "boxShadow": "none"
    }
  }
};