module.exports = {
  ".checkbox": {
    "&:checked": {
      "paddingY": "0px",
      "paddingX": "0px",
      "paddingTop": "0px",
      "paddingRight": "0px",
      "paddingBottom": "0px",
      "paddingLeft": "0px",
      "paddingStart": "0px",
      "paddingEnd": "0px",
      "spacing": "12px",
      "opacity": "1",
      "color": "#258cf2",
      "borderWidth": "1px",
      "borderRadius": "3px",
      "borderColor": "rgba(0, 0, 0, 0)",
      "width": "18px",
      "widthRaw": "18",
      "height": "18px",
      "heightRaw": "18"
    },
    "paddingY": "0px",
    "paddingX": "0px",
    "paddingTop": "0px",
    "paddingRight": "0px",
    "paddingBottom": "0px",
    "paddingLeft": "0px",
    "paddingStart": "0px",
    "paddingEnd": "0px",
    "spacing": "12px",
    "opacity": "1",
    "color": "rgba(0, 0, 0, 0)",
    "borderWidth": "1px",
    "borderRadius": "3px",
    "borderColor": "#b3b3b3",
    "width": "18px",
    "widthRaw": "18",
    "height": "18px",
    "heightRaw": "18",
    "&:disabled": {
      "paddingY": "0px",
      "paddingX": "0px",
      "paddingTop": "0px",
      "paddingRight": "0px",
      "paddingBottom": "0px",
      "paddingLeft": "0px",
      "paddingStart": "0px",
      "paddingEnd": "0px",
      "spacing": "12px",
      "opacity": "0.30000001192092896",
      "color": "#cccccc",
      "borderWidth": "1px",
      "borderRadius": "3px",
      "borderColor": "rgba(0, 0, 0, 0)",
      "width": "18px",
      "widthRaw": "18",
      "height": "18px",
      "heightRaw": "18"
    },
    "&:hover": {
      "paddingY": "0px",
      "paddingX": "0px",
      "paddingTop": "0px",
      "paddingRight": "0px",
      "paddingBottom": "0px",
      "paddingLeft": "0px",
      "paddingStart": "0px",
      "paddingEnd": "0px",
      "spacing": "12px",
      "opacity": "1",
      "color": "rgba(0, 0, 0, 0)",
      "borderWidth": "1px",
      "borderRadius": "3px",
      "borderColor": "#929292",
      "width": "18px",
      "widthRaw": "18",
      "height": "18px",
      "heightRaw": "18"
    }
  },
  ".checkbox-label": {
    "&:checked": {
      "fontFamily": "'Inter'",
      "fontSize": "14px",
      "fontWeight": "400",
      "lineHeight": "1.4285714721679688",
      "letterSpacing": "-0.28px",
      "textAlign": "left",
      "textDecoration": "none",
      "textTransform": "none",
      "color": "rgba(0, 0, 0, 0.8)",
      "opacity": "1"
    },
    "fontFamily": "'Inter'",
    "fontSize": "14px",
    "fontWeight": "400",
    "lineHeight": "1.4285714721679688",
    "letterSpacing": "-0.28px",
    "textAlign": "left",
    "textDecoration": "none",
    "textTransform": "none",
    "color": "#555555",
    "opacity": "1",
    "&:disabled": {
      "fontFamily": "'Inter'",
      "fontSize": "14px",
      "fontWeight": "400",
      "lineHeight": "1.4285714721679688",
      "letterSpacing": "-0.28px",
      "textAlign": "left",
      "textDecoration": "none",
      "textTransform": "none",
      "color": "#777777",
      "opacity": "1"
    },
    "&:hover": {
      "fontFamily": "'Inter'",
      "fontSize": "14px",
      "fontWeight": "400",
      "lineHeight": "1.4285714721679688",
      "letterSpacing": "-0.28px",
      "textAlign": "left",
      "textDecoration": "none",
      "textTransform": "none",
      "color": "rgba(0, 0, 0, 0.8)",
      "opacity": "1"
    }
  },
  ".checkbox-check": {
    "&:checked": {
      "borderWidth": "1px",
      "borderRadius": "3px",
      "borderColor": "rgba(0, 0, 0, 0)",
      "width": "18px",
      "widthRaw": "18",
      "height": "18px",
      "heightRaw": "18",
      "boxShadow": "none",
      "color": "#ffffff"
    },
    "borderWidth": "1px",
    "borderRadius": "3px",
    "borderColor": "#b3b3b3",
    "width": "18px",
    "widthRaw": "18",
    "height": "18px",
    "heightRaw": "18",
    "boxShadow": "none",
    "color": "#ffffff",
    "&:disabled": {
      "borderWidth": "1px",
      "borderRadius": "3px",
      "borderColor": "rgba(0, 0, 0, 0)",
      "width": "18px",
      "widthRaw": "18",
      "height": "18px",
      "heightRaw": "18",
      "boxShadow": "none",
      "color": "#ffffff"
    },
    "&:hover": {
      "borderWidth": "1px",
      "borderRadius": "3px",
      "borderColor": "#929292",
      "width": "18px",
      "widthRaw": "18",
      "height": "18px",
      "heightRaw": "18",
      "boxShadow": "none",
      "color": "#ffffff"
    }
  },
  ".checkbox-icon": {
    "&:checked": {
      "width": "12.599609375px",
      "widthRaw": "12.599609375",
      "height": "12.5999755859375px",
      "heightRaw": "12.5999755859375",
      "color": "#ffffff"
    },
    "width": "12.599609375px",
    "widthRaw": "12.599609375",
    "height": "12.5999755859375px",
    "heightRaw": "12.5999755859375",
    "color": "#ffffff"
  }
};