/** This exports all the components as Tailwinds Components for Handoff Preview. */ 

module.exports = [
  {
    ".btn-primary": {
      "background": "var(--button-primary-background)",
      "color": "var(--button-primary-color)",
      "paddingTop": "var(--button-primary-padding-top)",
      "paddingRight": "var(--button-primary-padding-right)",
      "paddingBottom": "var(--button-primary-padding-bottom)",
      "paddingLeft": "var(--button-primary-padding-left)",
      "borderWidth": "var(--button-primary-border-width)",
      "borderRadius": "var(--button-primary-border-radius)",
      "borderColor": "var(--button-primary-border-color)",
      "fontFamily": "var(--button-primary-font-family)",
      "fontSize": "var(--button-primary-font-size)",
      "fontWeight": "var(--button-primary-font-weight)",
      "lineHeight": "var(--button-primary-line-height)",
      "letterSpacing": "var(--button-primary-letter-spacing)",
      "textAlign": "var(--button-primary-text-align)",
      "textDecoration": "var(--button-primary-text-decoration)",
      "textTransform": "var(--button-primary-text-transform)",
      "boxShadow": "var(--button-primary-box-shadow)",
      "opacity": "var(--button-primary-opacity)",
      "$hover": {}
    }
  },
  {
    ".btn-custom-type": {
      "background": "var(--button-custom-type-background)",
      "color": "var(--button-custom-type-color)",
      "paddingTop": "var(--button-custom-type-padding-top)",
      "paddingRight": "var(--button-custom-type-padding-right)",
      "paddingBottom": "var(--button-custom-type-padding-bottom)",
      "paddingLeft": "var(--button-custom-type-padding-left)",
      "borderWidth": "var(--button-custom-type-border-width)",
      "borderRadius": "var(--button-custom-type-border-radius)",
      "borderColor": "var(--button-custom-type-border-color)",
      "fontFamily": "var(--button-custom-type-font-family)",
      "fontSize": "var(--button-custom-type-font-size)",
      "fontWeight": "var(--button-custom-type-font-weight)",
      "lineHeight": "var(--button-custom-type-line-height)",
      "letterSpacing": "var(--button-custom-type-letter-spacing)",
      "textAlign": "var(--button-custom-type-text-align)",
      "textDecoration": "var(--button-custom-type-text-decoration)",
      "textTransform": "var(--button-custom-type-text-transform)",
      "boxShadow": "var(--button-custom-type-box-shadow)",
      "opacity": "var(--button-custom-type-opacity)",
      "$hover": {}
    }
  },
  {
    ".btn-outline-secondary": {
      "background": "var(--button-outline-secondary-background)",
      "color": "var(--button-outline-secondary-color)",
      "paddingTop": "var(--button-outline-secondary-padding-top)",
      "paddingRight": "var(--button-outline-secondary-padding-right)",
      "paddingBottom": "var(--button-outline-secondary-padding-bottom)",
      "paddingLeft": "var(--button-outline-secondary-padding-left)",
      "borderWidth": "var(--button-outline-secondary-border-width)",
      "borderRadius": "var(--button-outline-secondary-border-radius)",
      "borderColor": "var(--button-outline-secondary-border-color)",
      "fontFamily": "var(--button-outline-secondary-font-family)",
      "fontSize": "var(--button-outline-secondary-font-size)",
      "fontWeight": "var(--button-outline-secondary-font-weight)",
      "lineHeight": "var(--button-outline-secondary-line-height)",
      "letterSpacing": "var(--button-outline-secondary-letter-spacing)",
      "textAlign": "var(--button-outline-secondary-text-align)",
      "textDecoration": "var(--button-outline-secondary-text-decoration)",
      "textTransform": "var(--button-outline-secondary-text-transform)",
      "boxShadow": "var(--button-outline-secondary-box-shadow)",
      "opacity": "var(--button-outline-secondary-opacity)",
      "$hover": {}
    }
  },
  {
    ".btn-danger": {
      "background": "var(--button-danger-background)",
      "color": "var(--button-danger-color)",
      "paddingTop": "var(--button-danger-padding-top)",
      "paddingRight": "var(--button-danger-padding-right)",
      "paddingBottom": "var(--button-danger-padding-bottom)",
      "paddingLeft": "var(--button-danger-padding-left)",
      "borderWidth": "var(--button-danger-border-width)",
      "borderRadius": "var(--button-danger-border-radius)",
      "borderColor": "var(--button-danger-border-color)",
      "fontFamily": "var(--button-danger-font-family)",
      "fontSize": "var(--button-danger-font-size)",
      "fontWeight": "var(--button-danger-font-weight)",
      "lineHeight": "var(--button-danger-line-height)",
      "letterSpacing": "var(--button-danger-letter-spacing)",
      "textAlign": "var(--button-danger-text-align)",
      "textDecoration": "var(--button-danger-text-decoration)",
      "textTransform": "var(--button-danger-text-transform)",
      "boxShadow": "var(--button-danger-box-shadow)",
      "opacity": "var(--button-danger-opacity)",
      "$hover": {}
    }
  },
  {
    ".btn-light": {
      "background": "var(--button-light-background)",
      "color": "var(--button-light-color)",
      "paddingTop": "var(--button-light-padding-top)",
      "paddingRight": "var(--button-light-padding-right)",
      "paddingBottom": "var(--button-light-padding-bottom)",
      "paddingLeft": "var(--button-light-padding-left)",
      "borderWidth": "var(--button-light-border-width)",
      "borderRadius": "var(--button-light-border-radius)",
      "borderColor": "var(--button-light-border-color)",
      "fontFamily": "var(--button-light-font-family)",
      "fontSize": "var(--button-light-font-size)",
      "fontWeight": "var(--button-light-font-weight)",
      "lineHeight": "var(--button-light-line-height)",
      "letterSpacing": "var(--button-light-letter-spacing)",
      "textAlign": "var(--button-light-text-align)",
      "textDecoration": "var(--button-light-text-decoration)",
      "textTransform": "var(--button-light-text-transform)",
      "boxShadow": "var(--button-light-box-shadow)",
      "opacity": "var(--button-light-opacity)",
      "$hover": {}
    }
  },
  {
    ".btn-dark": {
      "background": "var(--button-dark-background)",
      "color": "var(--button-dark-color)",
      "paddingTop": "var(--button-dark-padding-top)",
      "paddingRight": "var(--button-dark-padding-right)",
      "paddingBottom": "var(--button-dark-padding-bottom)",
      "paddingLeft": "var(--button-dark-padding-left)",
      "borderWidth": "var(--button-dark-border-width)",
      "borderRadius": "var(--button-dark-border-radius)",
      "borderColor": "var(--button-dark-border-color)",
      "fontFamily": "var(--button-dark-font-family)",
      "fontSize": "var(--button-dark-font-size)",
      "fontWeight": "var(--button-dark-font-weight)",
      "lineHeight": "var(--button-dark-line-height)",
      "letterSpacing": "var(--button-dark-letter-spacing)",
      "textAlign": "var(--button-dark-text-align)",
      "textDecoration": "var(--button-dark-text-decoration)",
      "textTransform": "var(--button-dark-text-transform)",
      "boxShadow": "var(--button-dark-box-shadow)",
      "opacity": "var(--button-dark-opacity)",
      "$hover": {}
    }
  },
  {
    ".btn-secondary": {
      "background": "var(--button-secondary-background)",
      "color": "var(--button-secondary-color)",
      "paddingTop": "var(--button-secondary-padding-top)",
      "paddingRight": "var(--button-secondary-padding-right)",
      "paddingBottom": "var(--button-secondary-padding-bottom)",
      "paddingLeft": "var(--button-secondary-padding-left)",
      "borderWidth": "var(--button-secondary-border-width)",
      "borderRadius": "var(--button-secondary-border-radius)",
      "borderColor": "var(--button-secondary-border-color)",
      "fontFamily": "var(--button-secondary-font-family)",
      "fontSize": "var(--button-secondary-font-size)",
      "fontWeight": "var(--button-secondary-font-weight)",
      "lineHeight": "var(--button-secondary-line-height)",
      "letterSpacing": "var(--button-secondary-letter-spacing)",
      "textAlign": "var(--button-secondary-text-align)",
      "textDecoration": "var(--button-secondary-text-decoration)",
      "textTransform": "var(--button-secondary-text-transform)",
      "boxShadow": "var(--button-secondary-box-shadow)",
      "opacity": "var(--button-secondary-opacity)",
      "$hover": {}
    }
  },
  {
    ".btn-primary": {
      "background": "var(--button-primary-background)",
      "color": "var(--button-primary-color)",
      "paddingTop": "var(--button-primary-padding-top)",
      "paddingRight": "var(--button-primary-padding-right)",
      "paddingBottom": "var(--button-primary-padding-bottom)",
      "paddingLeft": "var(--button-primary-padding-left)",
      "borderWidth": "var(--button-primary-border-width)",
      "borderRadius": "var(--button-primary-border-radius)",
      "borderColor": "var(--button-primary-border-color)",
      "fontFamily": "var(--button-primary-font-family)",
      "fontSize": "var(--button-primary-font-size)",
      "fontWeight": "var(--button-primary-font-weight)",
      "lineHeight": "var(--button-primary-line-height)",
      "letterSpacing": "var(--button-primary-letter-spacing)",
      "textAlign": "var(--button-primary-text-align)",
      "textDecoration": "var(--button-primary-text-decoration)",
      "textTransform": "var(--button-primary-text-transform)",
      "boxShadow": "var(--button-primary-box-shadow)",
      "opacity": "var(--button-primary-opacity)",
      "$hover": {}
    }
  },
  {
    ".btn-custom-type": {
      "background": "var(--button-custom-type-background)",
      "color": "var(--button-custom-type-color)",
      "paddingTop": "var(--button-custom-type-padding-top)",
      "paddingRight": "var(--button-custom-type-padding-right)",
      "paddingBottom": "var(--button-custom-type-padding-bottom)",
      "paddingLeft": "var(--button-custom-type-padding-left)",
      "borderWidth": "var(--button-custom-type-border-width)",
      "borderRadius": "var(--button-custom-type-border-radius)",
      "borderColor": "var(--button-custom-type-border-color)",
      "fontFamily": "var(--button-custom-type-font-family)",
      "fontSize": "var(--button-custom-type-font-size)",
      "fontWeight": "var(--button-custom-type-font-weight)",
      "lineHeight": "var(--button-custom-type-line-height)",
      "letterSpacing": "var(--button-custom-type-letter-spacing)",
      "textAlign": "var(--button-custom-type-text-align)",
      "textDecoration": "var(--button-custom-type-text-decoration)",
      "textTransform": "var(--button-custom-type-text-transform)",
      "boxShadow": "var(--button-custom-type-box-shadow)",
      "opacity": "var(--button-custom-type-opacity)",
      "$hover": {}
    }
  },
  {
    ".btn-outline-secondary": {
      "background": "var(--button-outline-secondary-background)",
      "color": "var(--button-outline-secondary-color)",
      "paddingTop": "var(--button-outline-secondary-padding-top)",
      "paddingRight": "var(--button-outline-secondary-padding-right)",
      "paddingBottom": "var(--button-outline-secondary-padding-bottom)",
      "paddingLeft": "var(--button-outline-secondary-padding-left)",
      "borderWidth": "var(--button-outline-secondary-border-width)",
      "borderRadius": "var(--button-outline-secondary-border-radius)",
      "borderColor": "var(--button-outline-secondary-border-color)",
      "fontFamily": "var(--button-outline-secondary-font-family)",
      "fontSize": "var(--button-outline-secondary-font-size)",
      "fontWeight": "var(--button-outline-secondary-font-weight)",
      "lineHeight": "var(--button-outline-secondary-line-height)",
      "letterSpacing": "var(--button-outline-secondary-letter-spacing)",
      "textAlign": "var(--button-outline-secondary-text-align)",
      "textDecoration": "var(--button-outline-secondary-text-decoration)",
      "textTransform": "var(--button-outline-secondary-text-transform)",
      "boxShadow": "var(--button-outline-secondary-box-shadow)",
      "opacity": "var(--button-outline-secondary-opacity)",
      "$hover": {}
    }
  },
  {
    ".btn-danger": {
      "background": "var(--button-danger-background)",
      "color": "var(--button-danger-color)",
      "paddingTop": "var(--button-danger-padding-top)",
      "paddingRight": "var(--button-danger-padding-right)",
      "paddingBottom": "var(--button-danger-padding-bottom)",
      "paddingLeft": "var(--button-danger-padding-left)",
      "borderWidth": "var(--button-danger-border-width)",
      "borderRadius": "var(--button-danger-border-radius)",
      "borderColor": "var(--button-danger-border-color)",
      "fontFamily": "var(--button-danger-font-family)",
      "fontSize": "var(--button-danger-font-size)",
      "fontWeight": "var(--button-danger-font-weight)",
      "lineHeight": "var(--button-danger-line-height)",
      "letterSpacing": "var(--button-danger-letter-spacing)",
      "textAlign": "var(--button-danger-text-align)",
      "textDecoration": "var(--button-danger-text-decoration)",
      "textTransform": "var(--button-danger-text-transform)",
      "boxShadow": "var(--button-danger-box-shadow)",
      "opacity": "var(--button-danger-opacity)",
      "$hover": {}
    }
  },
  {
    ".btn-light": {
      "background": "var(--button-light-background)",
      "color": "var(--button-light-color)",
      "paddingTop": "var(--button-light-padding-top)",
      "paddingRight": "var(--button-light-padding-right)",
      "paddingBottom": "var(--button-light-padding-bottom)",
      "paddingLeft": "var(--button-light-padding-left)",
      "borderWidth": "var(--button-light-border-width)",
      "borderRadius": "var(--button-light-border-radius)",
      "borderColor": "var(--button-light-border-color)",
      "fontFamily": "var(--button-light-font-family)",
      "fontSize": "var(--button-light-font-size)",
      "fontWeight": "var(--button-light-font-weight)",
      "lineHeight": "var(--button-light-line-height)",
      "letterSpacing": "var(--button-light-letter-spacing)",
      "textAlign": "var(--button-light-text-align)",
      "textDecoration": "var(--button-light-text-decoration)",
      "textTransform": "var(--button-light-text-transform)",
      "boxShadow": "var(--button-light-box-shadow)",
      "opacity": "var(--button-light-opacity)",
      "$hover": {}
    }
  },
  {
    ".btn-dark": {
      "background": "var(--button-dark-background)",
      "color": "var(--button-dark-color)",
      "paddingTop": "var(--button-dark-padding-top)",
      "paddingRight": "var(--button-dark-padding-right)",
      "paddingBottom": "var(--button-dark-padding-bottom)",
      "paddingLeft": "var(--button-dark-padding-left)",
      "borderWidth": "var(--button-dark-border-width)",
      "borderRadius": "var(--button-dark-border-radius)",
      "borderColor": "var(--button-dark-border-color)",
      "fontFamily": "var(--button-dark-font-family)",
      "fontSize": "var(--button-dark-font-size)",
      "fontWeight": "var(--button-dark-font-weight)",
      "lineHeight": "var(--button-dark-line-height)",
      "letterSpacing": "var(--button-dark-letter-spacing)",
      "textAlign": "var(--button-dark-text-align)",
      "textDecoration": "var(--button-dark-text-decoration)",
      "textTransform": "var(--button-dark-text-transform)",
      "boxShadow": "var(--button-dark-box-shadow)",
      "opacity": "var(--button-dark-opacity)",
      "$hover": {}
    }
  },
  {
    ".btn-secondary": {
      "background": "var(--button-secondary-background)",
      "color": "var(--button-secondary-color)",
      "paddingTop": "var(--button-secondary-padding-top)",
      "paddingRight": "var(--button-secondary-padding-right)",
      "paddingBottom": "var(--button-secondary-padding-bottom)",
      "paddingLeft": "var(--button-secondary-padding-left)",
      "borderWidth": "var(--button-secondary-border-width)",
      "borderRadius": "var(--button-secondary-border-radius)",
      "borderColor": "var(--button-secondary-border-color)",
      "fontFamily": "var(--button-secondary-font-family)",
      "fontSize": "var(--button-secondary-font-size)",
      "fontWeight": "var(--button-secondary-font-weight)",
      "lineHeight": "var(--button-secondary-line-height)",
      "letterSpacing": "var(--button-secondary-letter-spacing)",
      "textAlign": "var(--button-secondary-text-align)",
      "textDecoration": "var(--button-secondary-text-decoration)",
      "textTransform": "var(--button-secondary-text-transform)",
      "boxShadow": "var(--button-secondary-box-shadow)",
      "opacity": "var(--button-secondary-opacity)",
      "$hover": {}
    }
  }
];