module.exports = {
  ".modal-default": {
    "background": "#ffffff",
    "borderWidth": "1px",
    "borderRadius": "6px",
    "borderColor": "transparent",
    "paddingY": "0px",
    "paddingX": "0px",
    "paddingTop": "0px",
    "paddingRight": "0px",
    "paddingBottom": "0px",
    "paddingLeft": "0px",
    "paddingStart": "0px",
    "paddingEnd": "0px",
    "spacing": "0px",
    "boxShadow": "0px 3px 12px rgba(0, 0, 0, 0.05), 0px 4px 20px rgba(0, 0, 0, 0.1)"
  },
  ".modal-default-header": {
    "background": "transparent",
    "paddingY": "10px",
    "paddingX": "24px",
    "paddingTop": "20px",
    "paddingRight": "24px",
    "paddingBottom": "0px",
    "paddingLeft": "24px",
    "paddingStart": "24px",
    "paddingEnd": "24px",
    "spacing": "0px",
    "borderWidth": "1px",
    "borderRadius": "6px",
    "borderColor": "transparent",
    "boxShadow": "none"
  },
  ".modal-default-title": {
    "fontFamily": "'Inter'",
    "fontSize": "18px",
    "fontWeight": "700",
    "lineHeight": "1.6",
    "letterSpacing": "-0.36px",
    "textAlign": "center",
    "textDecoration": "none",
    "textTransform": "none",
    "color": "rgba(0, 0, 0, 0.8)"
  },
  ".modal-default-body": {
    "background": "transparent",
    "paddingY": "19px",
    "paddingX": "24px",
    "paddingTop": "10px",
    "paddingRight": "24px",
    "paddingBottom": "28px",
    "paddingLeft": "24px",
    "paddingStart": "24px",
    "paddingEnd": "24px",
    "spacing": "0px",
    "borderWidth": "1px",
    "borderRadius": "0px",
    "borderColor": "transparent",
    "boxShadow": "none"
  },
  ".modal-default-footer": {
    "background": "transparent",
    "paddingY": "12px",
    "paddingX": "24px",
    "paddingTop": "12px",
    "paddingRight": "24px",
    "paddingBottom": "12px",
    "paddingLeft": "24px",
    "paddingStart": "24px",
    "paddingEnd": "24px",
    "spacing": "0px",
    "borderWidth": "1px",
    "borderRadius": "0px",
    "borderColor": "#e8e8e8",
    "boxShadow": "none"
  }
};