module.exports = {
  ".radio-check": {
    "&:checked": {
      "width": "18px",
      "widthRaw": "18",
      "height": "18px",
      "heightRaw": "18",
      "paddingY": "0px",
      "paddingX": "0px",
      "paddingTop": "0px",
      "paddingRight": "0px",
      "paddingBottom": "0px",
      "paddingLeft": "0px",
      "paddingStart": "0px",
      "paddingEnd": "0px",
      "spacing": "0px"
    },
    "width": "18px",
    "widthRaw": "18",
    "height": "18px",
    "heightRaw": "18",
    "paddingY": "0px",
    "paddingX": "0px",
    "paddingTop": "0px",
    "paddingRight": "0px",
    "paddingBottom": "0px",
    "paddingLeft": "0px",
    "paddingStart": "0px",
    "paddingEnd": "0px",
    "spacing": "0px",
    "&:disabled": {
      "width": "18px",
      "widthRaw": "18",
      "height": "18px",
      "heightRaw": "18",
      "paddingY": "0px",
      "paddingX": "0px",
      "paddingTop": "0px",
      "paddingRight": "0px",
      "paddingBottom": "0px",
      "paddingLeft": "0px",
      "paddingStart": "0px",
      "paddingEnd": "0px",
      "spacing": "0px"
    },
    "&:hover": {
      "width": "18px",
      "widthRaw": "18",
      "height": "18px",
      "heightRaw": "18",
      "paddingY": "0px",
      "paddingX": "0px",
      "paddingTop": "0px",
      "paddingRight": "0px",
      "paddingBottom": "0px",
      "paddingLeft": "0px",
      "paddingStart": "0px",
      "paddingEnd": "0px",
      "spacing": "0px"
    }
  },
  ".radio-thumb": {
    "&:checked": {
      "width": "8px",
      "widthRaw": "8",
      "height": "8px",
      "heightRaw": "8",
      "color": "#ffffff",
      "borderWidth": "1px",
      "borderRadius": "0px",
      "borderColor": "transparent"
    },
    "width": "8px",
    "widthRaw": "8",
    "height": "8px",
    "heightRaw": "8",
    "color": "#ffffff",
    "borderWidth": "1px",
    "borderRadius": "0px",
    "borderColor": "transparent",
    "&:disabled": {
      "width": "8px",
      "widthRaw": "8",
      "height": "8px",
      "heightRaw": "8",
      "color": "#ffffff",
      "borderWidth": "1px",
      "borderRadius": "0px",
      "borderColor": "transparent"
    },
    "&:hover": {
      "width": "8px",
      "widthRaw": "8",
      "height": "8px",
      "heightRaw": "8",
      "color": "#ffffff",
      "borderWidth": "1px",
      "borderRadius": "0px",
      "borderColor": "transparent"
    }
  },
  ".radio-label": {
    "&:checked": {
      "fontFamily": "'Inter'",
      "fontSize": "14px",
      "fontWeight": "400",
      "lineHeight": "1.4285714721679688",
      "letterSpacing": "-0.28px",
      "textAlign": "left",
      "textDecoration": "none",
      "textTransform": "none",
      "opacity": "1"
    },
    "fontFamily": "'Inter'",
    "fontSize": "14px",
    "fontWeight": "400",
    "lineHeight": "1.4285714721679688",
    "letterSpacing": "-0.28px",
    "textAlign": "left",
    "textDecoration": "none",
    "textTransform": "none",
    "opacity": "1",
    "&:disabled": {
      "fontFamily": "'Inter'",
      "fontSize": "14px",
      "fontWeight": "400",
      "lineHeight": "1.4285714721679688",
      "letterSpacing": "-0.28px",
      "textAlign": "left",
      "textDecoration": "none",
      "textTransform": "none",
      "opacity": "1"
    },
    "&:hover": {
      "fontFamily": "'Inter'",
      "fontSize": "14px",
      "fontWeight": "400",
      "lineHeight": "1.4285714721679688",
      "letterSpacing": "-0.28px",
      "textAlign": "left",
      "textDecoration": "none",
      "textTransform": "none",
      "opacity": "1"
    }
  }
};