name: Deploy to production

on:
  push:
    branches: [main]
  # Manual Trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: json
      FIGMA_PROJECT_ID: ${{ secrets.FIGMA_PROJECT_ID }}
      DEV_ACCESS_TOKEN: ${{ secrets.DEV_ACCESS_TOKEN }}
      AWS_CLOUDFRONT_DIST_ID: ${{ secrets.AWS_DISTRIBUTION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set Git Defaults
        run: |
          git config --global user.email "ops@convertiv.com"
          git config --global user.name "Convertiv Development"
      - name: Fetch from figma
        run: |
          npm install --legacy-peer-deps
          npm run fetch
          git commit -a -m "[skip ci] updating changelog with latest figma changes"
          git push
      - name: Build static site
        run: |
          npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::581159614562:role/handoff-site-github-deploy-role
          aws-region: us-east-1
      - name: Deploy to S3 Bucket
        run: |
          aws s3 sync --delete dist/ s3://${{env.AWS_S3_BUCKET}}/
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION }} --paths /\*
        
